version: "3"
services:
   node-app:
      build: .
         #docker port and application port (localhost uses docker port)
      ports: 
         - "4444:4444"
      volumes:
         # YOU CANNOT TOUCH FILES FROM THE CONTAINER
         - .:/app:ro
         - /app/node_modules
      env_file:
         - ./.env

