version: "3"
services:
   nginx:
      image: nginx:stable-alpine
      container_name: nginx-c
      ports:
         - "4444:80"
      volumes:
         - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
   node-app:
      build: .
      container_name: node-app-c
      env_file:
         - ./.env
      depends_on:
         - mongo
         - redis
   mongo:
      image: mongo:4.4.10
      container_name: mongodb-c
      environment:
         - MONGO_INITDB_ROOT_USERNAME=faosl
         - MONGO_INITDB_ROOT_PASSWORD=1234
      volumes:
         - mongo-db:/data/db

   redis:
      image: redis
      container_name: redis-c

volumes:
   mongo-db:
